name: "Build Live USB ISO"

on: workflow_dispatch

jobs:
  build-live-usb-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - run: |
          nix build .#nixosConfigurations.liveusb.config.system.build.isoImage

      - uses: actions/upload-artifact@v2
        with:
          name: nixos-liveusb.iso
          path: ./result/iso/xmrig-liveusb.iso
